// clicker-react/src/App.tsx
import { produce } from "immer";
import { useSelector } from "react-redux";
import { useState } from "react";

import AchievementsTab from "./components/achievementsTab/AchievementsTab";
import { ACHIEVEMENTS } from "./gameElements/achievements";
import GameState from "./Gamestate";
import Game from "./components/game/Game";
import Options from "./components/options/Options";
import { RootState } from "./store/store";

import "./App.css";

function Navbar() {
  const money = useSelector((state: RootState) => state.money.value);
  const buildings = useSelector(
    (state: RootState) => state.buildings.buildings
  );

  const gameState: GameState = {
    money,
    buildings,
  };

  const [tabIndex, setTabIndex] = useState(0);
  const [achivements, setAchivements] = useState(ACHIEVEMENTS);
  const [alert, setAlert] = useState(false);

  achivements.forEach((achivement, index) => {
    if (!achivement.isDiscovered && achivement.condition(gameState)) {
      setAchivements(
        produce(achivements, (draft) => {
          draft[index].isDiscovered = true;
        })
      );
      setAlert(true);
    }
  });

  return (
    <div>
      <div className="tabs">
        <ul>
          <li className={tabIndex === 0 ? "is-active" : ""}>
            <a onClick={() => setTabIndex(0)}>Game</a>
          </li>
          <li className={tabIndex === 1 ? "is-active" : ""}>
            <a onClick={() => setTabIndex(1)}>Options</a>
          </li>
          <li className={tabIndex === 2 ? "is-active" : ""}>
            <a
              onClick={() => {
                setTabIndex(2);
                setAlert(false);
              }}
            >
              Achievements{" "}
              {alert && <span className="has-text-info">"NEW!"</span>}
            </a>
          </li>
        </ul>
      </div>

      <div className={tabIndex !== 0 ? "hidden" : ""}>
        <Game />
      </div>
      <div className={tabIndex !== 1 ? "hidden" : ""}>
        <Options />
      </div>
      <div className={tabIndex !== 2 ? "hidden" : ""}>
        <AchievementsTab achivements={achivements} />
      </div>
    </div>
  );
}

export default Navbar;

// clicker-vue/src/App.vue
<script setup lang="ts">
import Options from "./components/Options.vue"
import Game from "./components/Game.vue"
import Achievements from "./components/Achievements.vue"
import { onUpdated, ref } from "vue";
import { useGameStore } from "./store";
import { ACHIEVEMENTS } from "./achievements";

const store = useGameStore()

const tabIndex = ref(0);
const achievements = ref(ACHIEVEMENTS);
const alterted = ref(false);


function setTabIndex(index: number) {
  tabIndex.value = index;
}

function stopAlerted() {
  alterted.value = false;
}

onUpdated(() => {
  const gameState = { money: store.getMoney, buildings: store.getBuildings }

  achievements.value.forEach((achivement, index) => {
    if (!achivement.isDiscovered && achivement.condition(gameState)) {
      achievements.value[index].isDiscovered = true;
      alterted.value = true;
    }
  })

})

</script>

<template>
  <div class="tabs">
    <ul>
      <li :class="{ 'is-active': tabIndex === 0 }">
        <a @click="setTabIndex(0)">Game</a>
      </li>
      <li :class="{ 'is-active': tabIndex === 1 }">
        <a @click="setTabIndex(1)">Options</a>
      </li>
      <li :class="{ 'is-active': tabIndex === 2 }">
        <a @click="setTabIndex(2); stopAlerted()">
          Achievements <span v-if="alterted" class="has-text-info">NEWS!</span>
        </a>
      </li>
    </ul>
  </div>
  <div :class="{ hidden: tabIndex !== 0 }">
    <Game />
  </div>
  <div :class="{ hidden: tabIndex !== 1 }">
    <Options />
  </div>
  <div :class="{ hidden: tabIndex !== 2 }">
    <Achievements :achievements="achievements" />
  </div>
  <div v-if="store.getMoney < 0">{{ store.getMoney }}</div>
</template>

<style>
@import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";

.app {
  width: 100vw;
  height: 100vh;
}

.hidden {
  display: none;
}
</style>
