// clicker-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ACHIEVEMENTS } from './gameElements/achievements';
import { Observable } from 'rxjs';
import { Building } from './gameElements/buildings';
import { Store } from '@ngrx/store';
import { produce } from 'immer';
import { Achievement } from './gameElements/achievements';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  money$: Observable<number>;
  buildings$: Observable<Array<Building>>;

  money: number;
  buildings: Array<Building>;
  tabIndex = 0;

  achievements = ACHIEVEMENTS;
  alerted = false;

  constructor(
    private store: Store<{ money: number; buildings: Array<Building> }>
  ) {}

  ngOnInit() {
    this.money$ = this.store.select('money');
    this.buildings$ = this.store.select('buildings');

    this.money$.subscribe((money) => (this.money = money));
    this.buildings$.subscribe((buildings) => (this.buildings = buildings));
  }

  ngDoCheck() {
    const gameState = { money: this.money, buildings: this.buildings };

    this.achievements.forEach((achivement: Achievement, index: number) => {
      if (!achivement.isDiscovered && achivement.condition(gameState)) {
        this.achievements = produce(
          this.achievements,
          (draft: Array<Achievement>) => {
            draft[index].isDiscovered = true;
          }
        );
        this.alerted = true;
      }
    });
  }

  setTabIndex(num: number) {
    this.tabIndex = num;
  }
}

<div class="tabs">
  <ul>
    <li [class.is-active]="tabIndex === 0">
      <a (click)="setTabIndex(0)">Game</a>
    </li>
    <li [class.is-active]="tabIndex === 1">
      <a (click)="setTabIndex(1)">Options</a>
    </li>
    <li [class.is-active]="tabIndex === 2">
      <a (click)="setTabIndex(2); alerted = false">
        Achivements <span *ngIf="alerted" class="has-text-info">NEWS!</span>
      </a>
    </li>
  </ul>
</div>
<div [class.hidden]="tabIndex !== 0"><app-game /></div>
<div [class.hidden]="tabIndex !== 1"><app-options /></div>
<div [class.hidden]="tabIndex !== 2">
  <app-achivements-tab [achievements]="achievements" />
</div>

// clicker-react/src/App.tsx
import { produce } from "immer";
import { useSelector } from "react-redux";
import { useState } from "react";

import AchievementsTab from "./components/achievementsTab/AchievementsTab";
import { ACHIEVEMENTS } from "./gameElements/achievements";
import GameState from "./Gamestate";
import Game from "./components/game/Game";
import Options from "./components/options/Options";
import { RootState } from "./store/store";

import "./App.css";

function Navbar() {
  const money = useSelector((state: RootState) => state.money.value);
  const buildings = useSelector(
    (state: RootState) => state.buildings.buildings
  );

  const gameState: GameState = {
    money,
    buildings,
  };

  const [tabIndex, setTabIndex] = useState(0);
  const [achivements, setAchivements] = useState(ACHIEVEMENTS);
  const [alert, setAlert] = useState(false);

  achivements.forEach((achivement, index) => {
    if (!achivement.isDiscovered && achivement.condition(gameState)) {
      setAchivements(
        produce(achivements, (draft) => {
          draft[index].isDiscovered = true;
        })
      );
      setAlert(true);
    }
  });

  return (
    <div>
      <div className="tabs">
        <ul>
          <li className={tabIndex === 0 ? "is-active" : ""}>
            <a onClick={() => setTabIndex(0)}>Game</a>
          </li>
          <li className={tabIndex === 1 ? "is-active" : ""}>
            <a onClick={() => setTabIndex(1)}>Options</a>
          </li>
          <li className={tabIndex === 2 ? "is-active" : ""}>
            <a
              onClick={() => {
                setTabIndex(2);
                setAlert(false);
              }}
            >
              Achievements{" "}
              {alert && <span className="has-text-info">"NEW!"</span>}
            </a>
          </li>
        </ul>
      </div>

      <div className={tabIndex !== 0 ? "hidden" : ""}>
        <Game />
      </div>
      <div className={tabIndex !== 1 ? "hidden" : ""}>
        <Options />
      </div>
      <div className={tabIndex !== 2 ? "hidden" : ""}>
        <AchievementsTab achivements={achivements} />
      </div>
    </div>
  );
}

export default Navbar;
