// clicker-angular/src/app/game/game.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { changeMoneyByAmount } from '../store/money.actions';
import { Store } from '@ngrx/store';
import {
  Building,
  buildingShowingValue,
  buildingTruePrice,
  buildingsGain,
} from '../gameElements/buildings';
import { buyBuilding, unlockBuilding } from '../store/buildings.actions';

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['./game.component.css'],
})
export class GameComponent implements OnInit {
  money$: Observable<number>;
  buildings$: Observable<Array<Building>>;

  money: number;
  buildings: Array<Building>;
  buildingsGain: number;

  interval: number;
  date: Date = new Date();
  event: ((this: Document, ev: Event) => any) | null = null;

  constructor(
    private store: Store<{ money: number; buildings: Array<Building> }>
  ) {}

  ngOnInit() {
    this.money$ = this.store.select('money');
    this.buildings$ = this.store.select('buildings');

    this.money$.subscribe((money) => (this.money = money));

    this.buildings$.subscribe((buildings) => {
      this.buildingsGain = buildingsGain(buildings);
      this.buildings = buildings;
    });
  }

  ngDoCheck() {
    if (this.interval) {
      clearInterval(this.interval);
    }

    this.interval = window.setInterval(() => {
      this.store.dispatch(
        changeMoneyByAmount({ amount: this.buildingsGain / 10 })
      );
    }, 100);

    this.buildings.forEach((building) => {
      if (
        !building.isUnlocked &&
        buildingShowingValue(building) <= this.money
      ) {
        this.store.dispatch(unlockBuilding({ building }));
      }
    });

    if (this.event) {
      document.removeEventListener('visibilitychange', this.event);
    }
    this.event = () => {
      if (document.hidden) {
        console.log('hidden');
        this.date = new Date();
      } else {
        console.log('reveal');
        const nowDate = new Date();
        const delay = nowDate.getTime() - this.date.getTime();
        const reward = buildingsGain(this.buildings);
        this.store.dispatch(
          changeMoneyByAmount({ amount: reward * Math.floor(delay / 1000) })
        );
      }
    };
    document.addEventListener('visibilitychange', this.event);
  }

  ngOnDestroy() {
    if (this.interval) {
      clearInterval(this.interval);
    }
  }

  changeMoneyByAmount(amount: number) {
    this.store.dispatch(changeMoneyByAmount({ amount }));
  }

  buyBuilding(building: Building) {
    this.store.dispatch(buyBuilding({ building }));
    this.store.dispatch(
      changeMoneyByAmount({ amount: -buildingTruePrice(building) })
    );
  }

  buildingTruePrice(building: Building) {
    return buildingTruePrice(building);
  }

  buildingTitle(building: Building) {
    return `${building.desc} (${building.moneyGain} /s)`;
  }

  buildingShowingValue(building: Building) {
    return buildingShowingValue(building);
  }

  buildingsUnlocked() {
    return this.buildings.filter((building) => building.isUnlocked);
  }
}

<div class="columns">
  <div class="column is-one-third has-text-centered">
    <p class="is-size-1">
      Money : {{ money$ | async | formatNumber }} (+{{ buildingsGain }}/s)
      <!--{{ formatNumber(buildingsGain(store.getBuildings)) }}/s)-->
    </p>
    <button class="transparent-button" (click)="changeMoneyByAmount(1)">
      <img :src="assets/burger.png" alt="Click me!" />
    </button>
    <br />
    <button class="button" (click)="changeMoneyByAmount(1_000_000_000)">
      Cheat
    </button>
  </div>
  <div class="column">
    <div class="columns">
      <div class="column"></div>
    </div>
    <div *ngFor="let building of buildings$ | async" key="{building.id}">
      <app-hidden-element [minimalShow]="buildingShowingValue(building)">
        <button
          class="button max-width is-size-4"
          [title]="buildingTitle(building)"
          [disabled]="money < buildingTruePrice(building)"
          (click)="buyBuilding(building)"
        >
          {{ building.name }}({{ building.quantity }})
          {{ buildingTruePrice(building) | formatNumber }}
        </button>
      </app-hidden-element>
    </div>
  </div>
</div>

// clicker-react/src/components/game/Game.tsx
import { useEffect, useMemo, useState } from "react";
import "./Game.css";
import {
  buildingShowingValue,
  buildingTruePrice,
  buildingsGain,
} from "../../gameElements/buildings";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../../store/store";
import { changeByAmount } from "../../store/moneySlice";
import { buyBuilding, unlockBuilding } from "../../store/buildingSlice";
import burger from "../../assets/burger.png";

function App() {
  const money = useSelector((state: RootState) => state.money.value);
  const buildings = useSelector(
    (state: RootState) => state.buildings.buildings
  );
  const dispatch = useDispatch();

  const [date, setDate] = useState<Date>(new Date());

  buildings.forEach((building) => {
    if (!building.isUnlocked && money >= buildingShowingValue(building)) {
      dispatch(unlockBuilding(building));
    }
  });

  const display = useMemo(
    () =>
      new Intl.NumberFormat("en-GB", {
        notation: "compact",
        compactDisplay: "short",
      }),
    []
  );

  useEffect(() => {
    const interval = setInterval(() => {
      const reward = buildingsGain(buildings);
      dispatch(changeByAmount(reward / 10));
    }, 100);
    return () => clearInterval(interval);
  }, [buildings, dispatch]);

  useEffect(() => {
    const event = () => {
      if (document.hidden) {
        console.log("hidden");
        setDate(new Date());
      } else {
        console.log("reveal");
        const nowDate = new Date();
        const delay = nowDate.getTime() - date.getTime();
        const reward = buildingsGain(buildings);
        dispatch(changeByAmount(reward * Math.floor(delay / 1000)));
      }
    };
    document.addEventListener("visibilitychange", event);
    return () => document.removeEventListener("visibilitychange", event);
  }, [date, buildings, dispatch]);

  return (
    <>
      <div className="columns">
        <div className="column is-one-third  has-text-centered">
          <p className="is-size-1">
            Money : {display.format(money)} (+
            {display.format(buildingsGain(buildings))}/s)
          </p>
          <button
            className="transparent-button"
            onClick={() => dispatch(changeByAmount(1))}
          >
            <img src={burger} alt="Click me!" />
          </button>
          <br />
          <button
            className="button"
            onClick={() => dispatch(changeByAmount(1_000_000_000))}
          >
            Cheat
          </button>
        </div>
        <div className="column">
          <div className="columns">
            <div className="column"></div>
          </div>
          {buildings
            .filter((building) => building.isUnlocked)
            .map((building) => {
              const truePrice = buildingTruePrice(building);
              return (
                <div key={building.id}>
                  <button
                    className="button max-width is-size-4"
                    title={`${building.desc} (${building.moneyGain}/s)`}
                    disabled={money < truePrice}
                    onClick={() => {
                      dispatch(changeByAmount(Math.ceil(-truePrice)));
                      dispatch(buyBuilding(building));
                    }}
                  >
                    {building.name} ({building.quantity}){" "}
                    {display.format(truePrice)}
                  </button>
                </div>
              );
            })}
        </div>
      </div>
      <div className="columns">
        <div className="column is-one-quarter"></div>
        <div className="column"></div>
        <div className="column is-one-quarter"></div>
      </div>
    </>
  );
}

export default App;
