// clicker-react/src/Game.tsx
import { useEffect, useMemo } from "react";
import "./Game.css";
import {
  buildingShowingValue,
  buildingTruePrice,
  buildingsGain,
} from "./buildings";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "./store";
import { changeByAmount } from "./moneySlice";
import { buyBuilding } from "./buildingSlice";
import HideElement from "./utils/HideElement";
import burger from "./assets/burger.png";

function App() {
  const money = useSelector((state: RootState) => state.money.value);
  const buildings = useSelector(
    (state: RootState) => state.buildings.buildings
  );
  const dispatch = useDispatch();

  const display = useMemo(
    () =>
      new Intl.NumberFormat("en-GB", {
        notation: "compact",
        compactDisplay: "short",
      }),
    []
  );

  useEffect(() => {
    const interval = setInterval(() => {
      const reward = buildingsGain(buildings);
      dispatch(changeByAmount(reward / 10));
    }, 100);
    return () => clearInterval(interval);
  }, [buildings, dispatch]);

  return (
    <>
      <div className="columns">
        <div className="column is-one-third  has-text-centered">
          <p className="is-size-1">
            Money : {display.format(money)} (+
            {display.format(buildingsGain(buildings))}/s)
          </p>
          <button
            className="transparent-button"
            onClick={() => dispatch(changeByAmount(1))}
          >
            <img src={burger} alt="Click me!" />
          </button>
          <br />
          <button
            className="button"
            onClick={() => dispatch(changeByAmount(1_000_000_000))}
          >
            Cheat
          </button>
        </div>
        <div className="column">
          <div className="columns">
            <div className="column"></div>
          </div>
          {buildings.map((building) => {
            const truePrice = buildingTruePrice(building);
            return (
              <div key={building.id}>
                <HideElement minimalShow={buildingShowingValue(building)}>
                  <button
                    className="button max-width is-size-4"
                    title={`${building.desc} (${building.moneyGain}/s)`}
                    disabled={money < truePrice}
                    onClick={() => {
                      dispatch(changeByAmount(Math.ceil(-truePrice)));
                      dispatch(buyBuilding(building));
                    }}
                  >
                    {building.name} ({building.quantity}){" "}
                    {display.format(truePrice)}
                  </button>
                </HideElement>
              </div>
            );
          })}
        </div>
      </div>
      <div className="columns">
        <div className="column is-one-quarter"></div>
        <div className="column"></div>
        <div className="column is-one-quarter"></div>
      </div>
    </>
  );
}

export default App;

// clicker-vue/src/components/Game.vue
<script setup lang="ts">
import { Ref, onMounted, onUnmounted, onUpdated, ref } from 'vue';
import { useGameStore } from '../store';
import { Building, buildingTruePrice, buildingsGain, buildingShowingValue } from '../buildings';
import HideElement from "./HideElement.vue"
import burger from "../assets/burger.png";

const store = useGameStore()
let interval: Ref<number | null> = ref(null);

onMounted(() => {
  interval.value = setInterval(() => {
    store.changeMoneyByAmount(buildingsGain(store.getBuildings) / 10)
  }, 100)
})

onUpdated(() => {
  if (interval.value) {
    clearInterval(interval.value);
  }
  interval.value = setInterval(() => {
    store.changeMoneyByAmount(buildingsGain(store.getBuildings) / 10)
  }, 100)
})

onUnmounted(() => {
  if (interval.value) {
    clearInterval(interval.value);
  }
})


function buildingTitle(building: Building) {
  return `${building.desc} (${building.moneyGain} /s)`;
}

function buyBuilding(building: Building) {
  store.changeMoneyByAmount(Math.ceil(-buildingTruePrice(building)));
  store.buyBuilding(building);
}

function formatNumber(num: number) {
  const display = new Intl.NumberFormat("en-GB", {
    notation: "compact",
    compactDisplay: "short",
  });

  return display.format(num);
}
</script>

<template>
  <div class="columns">
    <div class="column is-one-third  has-text-centered">
      <p class="is-size-1">
        Money : {{ formatNumber(store.getMoney) }} (+
        {{ formatNumber(buildingsGain(store.getBuildings)) }}/s)
      </p>
      <button class="transparent-button" @click="store.changeMoneyByAmount(1)">
        <img :src="burger" alt="Click me!" />
      </button>
      <br />
      <button class="button" @click="store.changeMoneyByAmount(1_000_000_000)">
        Cheat
      </button>
    </div>
    <div class="column">
      <div class="columns">
        <div class="column"></div>
      </div>
      <div v-for="building in  store.getBuildings " key={building.id}>
        <HideElement :minimalShow="buildingShowingValue(building)">
          <button class="button max-width is-size-4" :title="buildingTitle(building)"
            :disabled="store.getMoney < buildingTruePrice(building)" @click="buyBuilding(building)">
            {{ building.name }}({{ building.quantity }}) {{ formatNumber(buildingTruePrice(building)) }}
          </button>
        </HideElement>
      </div>
    </div>
  </div>
</template>

<style scoped>
.max-width {
  width: 100%;
}

.transparent-button {
  border: none;
  background-color: transparent;
  cursor: pointer;
}
</style>
