// clicker-svelte/src/lib/Options.svelte
<script lang="ts">
  import burger from "../assets/burger.png";
  import { download } from "../utils/download";
  import { openFiles } from "../utils/openfiles";

  const { setGame, resetGame } = $$props;

  $: buildings = $$props.buildings;
  $: money = $$props.money;
  $: achievements = $$props.achievements;
</script>

<div>
  <button
    class="button"
    on:click={() => {
      resetGame();
    }}
  >
    Reset
  </button>
  <button
    class="button"
    on:click={() => {
      const gameState = { buildings, money, achievements };
      localStorage.setItem("save", JSON.stringify(gameState));
    }}
  >
    Save
  </button>
  <button
    class="button"
    on:click={() => {
      const save = localStorage.getItem("save");
      if (save !== null) {
        const state = JSON.parse(save);
        setGame(state);
      }
    }}
  >
    Load
  </button>
  <button class="button" on:click={() => {
    const gameState = { buildings, money, achievements };
    download("save.json", JSON.stringify(gameState));
  }}> Export </button>
  <button class="button" on:click={async () => {
    const files = await openFiles();
  const file = files[0];

  if (file) {
    const content = await file.text();
    const state = JSON.parse(content);
    setGame(state);
  }
  }}> Import </button>
</div>

<style>
</style>

// clicker-vue/src/components/Options.vue
<script setup lang="ts">
import { useGameStore } from '../store';
import { download, openFiles } from "../utils"

const store = useGameStore()

function reset() {
  store.resetMoney(); store.resetBuildings();
}

function save() {
  const state = {
    buildings: store.getBuildings,
    money: store.getMoney,
  };
  localStorage.setItem("save", JSON.stringify(state));
}

function load() {
  const save = localStorage.getItem("save");
  if (save !== null) {
    const state = JSON.parse(save);
    store.setMoney(state.money);
    store.setBuildings(state.buildings);
  }

}

function exportSave() {
  const state = {
    buildings: store.getBuildings,
    money: store.getMoney,
  };
  download("save.json", JSON.stringify(state));
}

async function importSave() {
  const files = await openFiles();
  const file = files[0];

  if (file) {
    const content = await file.text();
    const state = JSON.parse(content);
    store.setMoney(state.money);
    store.setBuildings(state.buildings);
  }

}
</script>

<template>
  <button class="button" @click="reset">
    Reset
  </button>
  <button class="button" @click="save">
    Save
  </button>
  <button class="button" @click="load">
    Load
  </button>
  <button class="button" @click="exportSave">
    Export
  </button>
  <button class="button" @click="importSave">
    Import
  </button>
</template>

<style scoped></style>
